name: pull_request

on:
  pull_request:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: installing
        run: npm ci

      - name: building
        run: npm run build:src && npm run build:docs -- --public-url /ant-design-icons/ && npm run build:lib
